name: rxdart_example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.2
  logger: ^1.1.0
  retrofit: ^2.2.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  equatable: ^2.0.3
  injectable: ^1.5.0
  flutter_bloc: ^7.3.1
  get_it: ^7.2.0

dev_dependencies:
  dart_code_metrics: ^4.9.1 
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^2.1.0+1
  build_runner: ^2.1.4
  injectable_generator: ^1.5.2


flutter:
  uses-material-design: true
